# Generated by Django 2.2.5 on 2020-06-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias_Horario',
            fields=[
                ('id_dia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': ('Dias_Semanal',),
                'verbose_name_plural': ('Dias',),
                'db_table': 'hms_Dias_Horario',
            },
        ),
        migrations.CreateModel(
            name='MateriasAfines',
            fields=[
                ('id_materias_afines', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('Materias Afines',),
                'verbose_name_plural': ('Materias Afines',),
                'db_table': 'hms_materias_afiness',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('sintesis_cv', models.TextField(blank=True, default='No definido', null=True)),
                ('currirrulum', models.FileField(blank=True, null=True, upload_to='anexos_tutor/')),
                ('id_materias_afines', models.ManyToManyField(blank=True, db_table='hms_usuario_materias_detalle', null=True, to='tutor.MateriasAfines')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_tutor', to='seguridad.Usuario')),
            ],
            options={
                'verbose_name': ('tutor',),
                'verbose_name_plural': ('tutor',),
                'db_table': 'hms_tutor',
            },
        ),
        migrations.CreateModel(
            name='ValorPorHora',
            fields=[
                ('idValorPorHora', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(blank=True, max_length=50, null=True)),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valor_tutor', to='tutor.Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios_tutor',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, max_length=10, null=True)),
                ('dias', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio', models.TimeField(blank=True, default='00:00:00', null=True)),
                ('hora_fin', models.TimeField(blank=True, default='00:00:00', null=True)),
                ('prescencial', models.BooleanField(blank=True, default=False, null=True)),
                ('virtual', models.BooleanField(blank=True, default=False, null=True)),
                ('tutor', models.ForeignKey(db_column='id_tutor', on_delete=django.db.models.deletion.CASCADE, related_name='tutor_horarios', to='tutor.Tutor')),
            ],
            options={
                'db_table': 'Horarios_tutor',
            },
        ),
        migrations.CreateModel(
            name='Experiencia_tutor',
            fields=[
                ('id_experiencia', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_empleo', models.CharField(blank=True, choices=[('MT', 'MEDIO TIEMPO'), ('TP', 'TIEMPO COMPLETO')], max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, max_length=100, null=True)),
                ('fecha_fin', models.DateField(blank=True, max_length=100, null=True)),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienciaTutor', to='tutor.Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Educacion_tutor',
            fields=[
                ('id_experiencia_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('universidad', models.CharField(blank=True, max_length=50, null=True)),
                ('titulacion', models.CharField(blank=True, max_length=50, null=True)),
                ('nota', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, max_length=100, null=True)),
                ('fecha_fin', models.DateField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educacionTutor', to='tutor.Tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion_tutor',
            fields=[
                ('id_certificado_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_certificado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, max_length=100, null=True)),
                ('fecha_fin', models.DateField(blank=True, max_length=100, null=True)),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificadoTutor', to='tutor.Tutor')),
            ],
        ),
    ]
