# Generated by Django 2.2.5 on 2020-08-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='calificacion',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
