# Generated by Django 2.2.4 on 2021-03-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutor_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacion_tutor',
            name='origen',
            field=models.CharField(blank=True, default='no definido', max_length=50, null=True),
        ),
    ]
