# Generated by Django 2.2.4 on 2021-03-08 07:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_certificacion_tutor_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='transacciones_log',
            fields=[
                ('id_trx', models.AutoField(primary_key=True, serialize=False)),
                ('fechora_trx', models.DateField(blank=True, default=datetime.datetime(2021, 3, 8, 2, 6, 34, 625424), max_length=100, null=True)),
                ('secuencial', models.DateField(blank=True, max_length=100, null=True)),
                ('cod_resultado', models.CharField(blank=True, default='000', max_length=3, null=True)),
                ('mensaje_log', models.CharField(blank=True, default='Transacción OK', max_length=150, null=True)),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trxTutor', to='tutor.Tutor')),
            ],
        ),
    ]
