# Generated by Django 2.2.4 on 2021-03-08 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_transacciones_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones_log',
            name='fechora_trx',
            field=models.DateField(blank=True, default=datetime.datetime.now, max_length=100, null=True),
        ),
    ]
