# Generated by Django 2.2.4 on 2021-03-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_auto_20210308_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones_log',
            name='comision',
            field=models.CharField(default='0.00', max_length=4),
        ),
        migrations.AddField(
            model_name='transacciones_log',
            name='valor_pagado',
            field=models.CharField(default='0.00', max_length=4),
        ),
        migrations.AddField(
            model_name='transacciones_log',
            name='valor_total',
            field=models.CharField(default='0.00', max_length=4),
        ),
    ]
