# Generated by Django 2.2.4 on 2021-03-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_auto_20210308_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones_log',
            name='procesado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
