# Generated by Django 2.2.4 on 2021-03-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_transacciones_log_procesado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transacciones_log',
        ),
    ]
