# Generated by Django 2.2.5 on 2020-06-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': ('estudiante',),
                'verbose_name_plural': ('estudiante',),
                'db_table': 'hms_estudiante',
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id_representante', models.AutoField(primary_key=True, serialize=False)),
                ('nombresr', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidosr', models.CharField(blank=True, max_length=50, null=True)),
                ('identificacionr', models.CharField(blank=True, default='No definido', max_length=50, null=True)),
                ('correor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimientor', models.DateField(blank=True, max_length=50, null=True)),
                ('generor', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=50, null=True)),
                ('ciudadr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridad.Ciudad')),
                ('paisr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridad.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Academico',
            fields=[
                ('id_niveles_academicos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, choices=[('Educacion Basica', 'Educacion Basica'), ('Escuela Secundaria', 'Escuela Secundaria'), ('Tecnico Avanzado', 'Tecnico Avanzado'), ('Tercer Nivel', 'Tercer Nivel'), ('Postgrado', 'Postgrado')], max_length=100, null=True)),
                ('id_estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nivelesEstudiante', to='estudiante.Estudiante')),
            ],
        ),
    ]
