# Generated by Django 2.2.5 on 2020-06-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor', '0001_initial'),
        ('estudiante', '0001_initial'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='id_materias_afines',
            field=models.ManyToManyField(blank=True, db_table='hms_ematerias_det', null=True, to='tutor.MateriasAfines'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Representante'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_estudiante', to='seguridad.Usuario'),
        ),
    ]
