# Generated by Django 2.2.5 on 2020-07-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_auto_20200617_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='apellidosr',
            field=models.CharField(blank=True, default='No definido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='correor',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='nombresr',
            field=models.CharField(blank=True, default='No definido', max_length=50, null=True),
        ),
    ]
