# Generated by Django 2.2.5 on 2020-07-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_auto_20200703_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tutoria_online',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tutoria_prescencial',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
