# Generated by Django 2.2.5 on 2020-07-23 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('estudiante', '0004_auto_20200703_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAsignado',
            fields=[
                ('id_tutorAsignado', models.AutoField(primary_key=True, serialize=False)),
                ('id_estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_asignado', to='estudiante.Estudiante')),
                ('id_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_asignado', to='tutor.Tutor')),
            ],
        ),
    ]
