# Generated by Django 2.2.5 on 2020-07-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_tutorasignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorasignado',
            name='estado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tutorasignado',
            name='fecha_contacto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
