# Generated by Django 2.2.4 on 2020-08-10 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('estudiante', '0006_auto_20200726_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionEstudiante',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta_1', models.IntegerField(blank=True, default=0, null=True)),
                ('pregunta_2', models.IntegerField(blank=True, default=0, null=True)),
                ('pregunta_3', models.IntegerField(blank=True, default=0, null=True)),
                ('pregunta_4', models.IntegerField(blank=True, default=0, null=True)),
                ('pregunta_5', models.IntegerField(blank=True, default=0, null=True)),
                ('id_estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_evaluacion', to='estudiante.Estudiante')),
                ('id_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_evaluacion', to='tutor.Tutor')),
            ],
        ),
    ]
