# Generated by Django 2.2.4 on 2020-08-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0007_evaluacionestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionestudiante',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
