# Generated by Django 2.2.4 on 2020-08-11 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0008_evaluacionestudiante_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionestudiante',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
