# Generated by Django 2.2.4 on 2020-08-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0009_auto_20200810_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionestudiante',
            name='pregunta_1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionestudiante',
            name='pregunta_2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionestudiante',
            name='pregunta_3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionestudiante',
            name='pregunta_4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionestudiante',
            name='pregunta_5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
