# Generated by Django 2.2.4 on 2020-08-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0011_evaluacionestudiante_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionestudiante',
            name='comentario_negativo',
            field=models.TextField(blank=True, default='No has realizado ningun comentario aun', null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionestudiante',
            name='comentario',
            field=models.TextField(blank=True, default='No has realizado ningun comentario aun', null=True),
        ),
    ]
