# Generated by Django 2.2.4 on 2021-03-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutor_calificacion'),
        ('estudiante', '0012_auto_20200810_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoClases',
            fields=[
                ('id_seg', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio', models.TimeField(blank=True, default='00:00:00', null=True)),
                ('hora_fin', models.TimeField(blank=True, default='00:00:00', null=True)),
                ('procesado', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=False)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seg_est', to='estudiante.Estudiante')),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seg_tutor', to='tutor.Tutor')),
            ],
        ),
    ]
