# Generated by Django 2.2.5 on 2020-06-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('Ciudad',),
                'verbose_name_plural': ('Ciudades',),
                'db_table': 'hms_ciudades',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('Pais',),
                'verbose_name_plural': ('Paises',),
                'db_table': 'hms_paises',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('identificacion', models.CharField(blank=True, default='No definido', max_length=50, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, max_length=50, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridad.Ciudad')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridad.Pais')),
            ],
            options={
                'verbose_name': ('Persona',),
                'verbose_name_plural': ('Personas',),
                'db_table': 'hms_personas',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': ('Rol',),
                'verbose_name_plural': ('Roles',),
                'db_table': 'hms_roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='persona_usuario', to='seguridad.Persona')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Rol')),
            ],
            options={
                'verbose_name': ('Usuario',),
                'verbose_name_plural': ('Usuario',),
                'db_table': 'hms_usuarios',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('id_rol', models.ManyToManyField(db_table='id_rol', to='seguridad.Rol')),
            ],
            options={
                'verbose_name': ('Permiso',),
                'verbose_name_plural': ('Permisos',),
                'db_table': 'hms_permisos',
            },
        ),
    ]
