# Generated by Django 2.2.5 on 2020-06-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='id_rol',
            field=models.ManyToManyField(db_table='roles_permisos', to='seguridad.Rol'),
        ),
    ]
