# Generated by Django 2.2.5 on 2020-06-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_auto_20200617_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
