# Generated by Django 2.2.5 on 2020-07-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_auto_20200703_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='clave',
            field=models.CharField(blank=True, default='user_login_google', max_length=600, null=True),
        ),
    ]
