# Generated by Django 2.2.4 on 2020-08-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_auto_20200705_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default='static/profile_default.jpg', upload_to='fotos_perfil'),
        ),
    ]
