# Generated by Django 2.2.4 on 2020-08-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_persona_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default='static/profile_default.jpg', upload_to='fotos_perfil/'),
        ),
    ]
