# Generated by Django 2.2.4 on 2020-08-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0008_auto_20200805_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default='profile_default.jpg', upload_to='fotos_perfil/'),
        ),
    ]
